In [1]:
import numpy as np

rev_usd = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
rev_inr = np.array([75])
rev_usd*rev_inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [8]:
price_per_unit = np.array([20,30,15])
units = np.array([[50,60,25],[10,13,5],[40,70,52]])
total_sales = units*price_per_unit

print(total_sales)
#wrong computation because of using rows of the matrix

[[1000 1800  375]
 [ 200  390   75]
 [ 800 2100  780]]


In [6]:
#total sales as a scala
units = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit = np.array([20,30,15])

total_sales = np.dot(price_per_unit,units)

print(total_sales)
#right operation to get totl sales of flowers per month

[1900 2640 1430]


In [10]:
#wrong computation
price_per_unit = np.array([20,30,15])
units = np.array([[50,10,40],[60,13,70],[25,5,52]])
total_sales = units*price_per_unit

print(total_sales)

[3175  665 3680]


In [13]:
#replacing nan
data = np.array([[1, 2, 3], [4, np.nan, 6], [7, 8, 9]])
mean = np.nanmean(data, axis=0)

mean


array([4., 5., 6.])

In [20]:
#singular value decomposition
data = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])

np.linalg.svd(data, full_matrices=False, compute_uv=True, hermitian=False)

u, s, v = np.linalg.svd(data)
k = 2
reduced_data = u[:, :k] @ np.diag(s[:k]) @ v[:k, :]

reduced_data

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [1]:
#covariance
financial_data = np.array([[100, 5, 500, 0.02], [120, 6, 550, 0.015], [90, 4, 480, 0.025]])
financial_data_transposed = financial_data.T

covariance_matrix = np.cov(financial_data_transposed)

print("Covariance Matrix:")
print(covariance_matrix)

max_covariance_indices = np.unravel_index(np.argmax(covariance_matrix), covariance_matrix.shape)


feature_names = ['Stock Price', 'Earnings per Share', 'Market Cap', 'Volatility']
feature1_name = feature_names[max_covariance_indices[0]]
feature2_name = feature_names[max_covariance_indices[1]]

max_covariance_value = covariance_matrix[max_covariance_indices]

print(f"\nThe largest positive covariance is between '{feature1_name}'")

NameError: name 'np' is not defined

In [ ]:
#optimal resource allocation
A = np.array([[2,3],[4,5]])
b = np.array([100,200])
inverse = np.linalg.inv(A)
p = np.dot(inverse,b)
p