In [1]:
import numpy as np

revenue = np.array([[180, 240, 220], [200, 360, 180], [220, 400, 200]])
expenses = np.array([[80, 10, 8], [90, 16, 10], [100, 20, 10]])

profit_loss = revenue - expenses
print(profit_loss)


[[100 230 212]
 [110 344 170]
 [120 380 190]]


In [5]:
#dot product
price = np.array([1000, 400, 1200])
units = np.array([[30,5,2],[40,10,5],[50,15,7]])

mult = price*units
print(mult)
#read more on numpy broadcasting

dot_product = np.dot(price,units)
print(dot_product)

[[30000  2000  2400]
 [40000  4000  6000]
 [50000  6000  8400]]
[106000  27000  12400]
