In [1]:
import numpy as np

#transpose a matrix(switch rows with columns)
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
transpose_matrix = np.transpose(matrix)
print(transpose_matrix)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [2]:
#matrix determinant. The determinant is a scala
#value that can be computed
matrix = np.array([[3,1], [2,4]])
determinant_value = np.linalg.det(matrix)
print(determinant_value)

10.000000000000002


In [3]:
#matrix inversion. Finding a matrix which
#when multiplied with it i should get an identity matrix
matrix = np.array([[4,7], [2,6]])
inverse_value = np.linalg.inv(matrix)
print(inverse_value)

[[ 0.6 -0.7]
 [-0.2  0.4]]


In [4]:
#eigen values and eigen vectors
matrix = np.array([[4,2], [1,3]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues, eigenvectors)

[5. 2.] [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
