In [5]:
import numpy as np

list1 = [1,2,3,4,5]
list2 = [5,4,3,2,1]

#vectors
v1 = np.array(list1)
v2 = np.array(list2)

#in addition the length of the vectors must be the same
v_add = v1+v2
print(v_add)

#in addition order matters
v_sub = v1-v2
print(v_sub)

#multiplication
v_mul = v1*v2
print(v_mul)

#dot product
v_dot_product = v1 @ v2
print(v_dot_product)

#cross product. Must be 2 or 3 dimensional
list3 = [1,2,3]
list4 = [4,5,6]

v_cross = np.cross(list3, list4)
print(v_cross)

#5 dimensional list multiplied by a scala
list5 = [10,20,30,40,50]
v3 = np.array(list5)
#scala
x = 2

mult = v3*x
print(mult)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]
35
[-3  6 -3]
[ 20  40  60  80 100]
